# Generated by Django 2.0.4 on 2018-04-27 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoisspy', '0002_auto_20180424_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='group',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='group',
            field=models.ManyToManyField(blank=True, to='whoisspy.Group'),
        ),
    ]
